[package]
name = "fractals"
version = "0.1.0"
edition = "2021"

[dependencies]
pixels = "0.13"
winit = "0.28"
egui = "0.22"
egui-winit = "0.22"
egui_glow = "0.22" # Official GL backend for egui
rayon = "1.8"
rand = "0.8"